MSG_FIELD_KO = 'El fitxer no existeix en aquesta ruta!'
NOM = 'Introdueix el nom del fitxer:'
CONTINGUT = 'Introdueix el contingut:'
FITXER = 'Demanem el fitxer'
MOSTRAR = 'El contingut del fitxer es el següent:'
NOMBRE = 'Introdueix el teu nom:'
APELLIDO = 'Introdueix el primer cognom:'
EDAD = 'Introdueix la teva edat:'
MENU = 'Indica la tecnologia interesa:\n\t1.-IT\n\t2.-Big Data\n\t3.-Web Developer\n'
MENUCSV = 'Indica la opció a escogir entre:\n\t1.-Llegir un CSV\n\t2.-Afegir dades al CSV\n'
LLEGIR = 'Demanem arxiu per llegir'
TXT = "El contingut del fitxer és el següent:"
ALTRES = "A continuació, introdueix altres dades al fitxer:"
CURS = "Indica el curs:"
AULA = "Indica el num de l'aula:"
NALUM = "Indica el num d'alumnes:"
NPROF = "Indica el num de professors:"
HORA = "Introdueix l'hora:"
NOMPROF = "Introdueix el nom del professor:"
ASSIG = "Introdueix el nom de l'assignatura:"
DIA = "Introdueix el dia:"
CO2 = "Introdueix el CO2 (ppm):"
TEMP = "Introdueix la temperatura:"
HUMITAT = "Introdueix la humitat relativa:"
FSESSIO = "S'ha finalitzat la classe?\n\t 1.-Si\n\t 2.-No"
PP = "Quants mins ha estat la porta principal oberta?"
PS = "Quants mins ha estat la porta secundaria oberta?"
PSEC = "Té porta secundaria?\n\t1.-Si\n\t2.-No"
FEXT = "Quants mins ha estat les finestres exteriors obertes?"
FINESTRES_EXT = "Hi han finestres exteriors?\n\t 1.-Si\n\t 2.-No"
FINESTRES_INT = "Hi han finestres interiors?\n\t 1.-Si\n\t 2.-No"
FINT = "Quants mins ha estat les finestres interiors obertes?"
VENTILACIO = "Indica si s'ha produit una ventilació creuada en algun moment:"
